
#include "nightpch.h"
#include "ActionMapping.h"

namespace night
{
	map<string, InputKey> string_to_input_key_map =
	{
		{ "Key Invalid", InputKey(EKey::Invalid)  },

		{ "Key A", InputKey(EKey::A)  },
		{ "Key B", InputKey(EKey::B)  },
		{ "Key C", InputKey(EKey::C)  },
		{ "Key D", InputKey(EKey::D)  },
		{ "Key E", InputKey(EKey::E)  },
		{ "Key F", InputKey(EKey::F)  },
		{ "Key G", InputKey(EKey::G)  },
		{ "Key H", InputKey(EKey::H)  },
		{ "Key I", InputKey(EKey::I)  },
		{ "Key J", InputKey(EKey::J)  },
		{ "Key K", InputKey(EKey::K)  },
		{ "Key L", InputKey(EKey::L)  },
		{ "Key M", InputKey(EKey::M)  },
		{ "Key N", InputKey(EKey::N)  },
		{ "Key O", InputKey(EKey::O)  },
		{ "Key P", InputKey(EKey::P)  },
		{ "Key Q", InputKey(EKey::Q)  },
		{ "Key R", InputKey(EKey::R)  },
		{ "Key S", InputKey(EKey::S)  },
		{ "Key T", InputKey(EKey::T)  },
		{ "Key U", InputKey(EKey::U)  },
		{ "Key V", InputKey(EKey::V)  },
		{ "Key W", InputKey(EKey::W)  },
		{ "Key X", InputKey(EKey::X)  },
		{ "Key Y", InputKey(EKey::Y)  },
		{ "Key Z", InputKey(EKey::Z)  },

		{ "Key N1", InputKey(EKey::N1)  },
		{ "Key N2", InputKey(EKey::N2)  },
		{ "Key N3", InputKey(EKey::N3)  },
		{ "Key N4", InputKey(EKey::N4)  },
		{ "Key N5", InputKey(EKey::N5)  },
		{ "Key N6", InputKey(EKey::N6)  },
		{ "Key N7", InputKey(EKey::N7)  },
		{ "Key N8", InputKey(EKey::N8)  },
		{ "Key N9", InputKey(EKey::N9)  },
		{ "Key N0", InputKey(EKey::N0)  },

		{"Key Return", InputKey(EKey::Return)  },
		{"Key Escape", InputKey(EKey::Escape)  },
		{"Key BackSpace", InputKey(EKey::BackSpace)  },
		{"Key Tab", InputKey(EKey::Tab)  },
		{"Key Space", InputKey(EKey::Space)  },

		{"Key Minus", InputKey(EKey::Minus)  },
		{"Key Equals", InputKey(EKey::Equals)  },
		{"Key LeftBracket", InputKey(EKey::LeftBracket)  },
		{"Key RightBracket", InputKey(EKey::RightBracket)  },
		{"Key BackSlash", InputKey(EKey::BackSlash)  },

		{"Key NonUSHash", InputKey(EKey::NonUSHash)  },

		{"Key SemiColon", InputKey(EKey::SemiColon)  },
		{"Key Apostrophe", InputKey(EKey::Apostrophe)  },
		{"Key Grave", InputKey(EKey::Grave)  },

		{"Key Comma", InputKey(EKey::Comma)  },
		{"Key Period", InputKey(EKey::Period)  },
		{"Key Slash", InputKey(EKey::Slash)  },

		{"Key CapsLock", InputKey(EKey::CapsLock)  },

		{"Key F1", InputKey(EKey::F1)  },
		{"Key F2", InputKey(EKey::F2)  },
		{"Key F3", InputKey(EKey::F3)  },
		{"Key F4", InputKey(EKey::F4)  },
		{"Key F5", InputKey(EKey::F5)  },
		{"Key F6", InputKey(EKey::F6)  },
		{"Key F7", InputKey(EKey::F7)  },
		{"Key F8", InputKey(EKey::F8)  },
		{"Key F9", InputKey(EKey::F9)  },
		{"Key F10", InputKey(EKey::F10)  },
		{"Key F11", InputKey(EKey::F11)  },
		{"Key F12", InputKey(EKey::F12)  },

		{"Key PrintScreen", InputKey(EKey::PrintScreen)  },
		{"Key ScrollLock", InputKey(EKey::ScrollLock)  },
		{"Key Pause", InputKey(EKey::Pause)  },
		{"Key Insert", InputKey(EKey::Insert)  },

		{"Key Home", InputKey(EKey::Home)  },
		{"Key PageUp", InputKey(EKey::PageUp)  },
		{"Key Delete", InputKey(EKey::Delete)  },
		{"Key End", InputKey(EKey::End)  },
		{"Key PageDown", InputKey(EKey::PageDown)  },
		{"Key Right", InputKey(EKey::Right)  },
		{"Key Left", InputKey(EKey::Left)  },
		{"Key Down", InputKey(EKey::Down)  },
		{"Key Up", InputKey(EKey::Up)  },

		{"Key NumLockClear", InputKey(EKey::NumLockClear)  },

		{"Key KP_Divide", InputKey(EKey::KP_Divide)  },
		{"Key KP_Multiply", InputKey(EKey::KP_Multiply)  },
		{"Key KP_Minus", InputKey(EKey::KP_Minus)  },
		{"Key KP_Plus", InputKey(EKey::KP_Plus)  },
		{"Key KP_Enter", InputKey(EKey::KP_Enter)  },
		{"Key KP_1", InputKey(EKey::KP_1)  },
		{"Key KP_2", InputKey(EKey::KP_2)  },
		{"Key KP_3", InputKey(EKey::KP_3)  },
		{"Key KP_4", InputKey(EKey::KP_4)  },
		{"Key KP_5", InputKey(EKey::KP_5)  },
		{"Key KP_6", InputKey(EKey::KP_6)  },
		{"Key KP_7", InputKey(EKey::KP_7)  },
		{"Key KP_8", InputKey(EKey::KP_8)  },
		{"Key KP_9", InputKey(EKey::KP_9)  },
		{"Key KP_0", InputKey(EKey::KP_0)  },
		{"Key KP_Period", InputKey(EKey::KP_Period)  },

		{"Key NonUSBackSlash", InputKey(EKey::NonUSBackSlash)  },

		{"Key Application", InputKey(EKey::Application)  },
		{"Key Power", InputKey(EKey::Power)  },

		{"Key KP_Equals", InputKey(EKey::KP_Equals)  },
		{"Key F13", InputKey(EKey::F13)  },
		{"Key F14", InputKey(EKey::F14)  },
		{"Key F15", InputKey(EKey::F15)  },
		{"Key F16", InputKey(EKey::F16)  },
		{"Key F17", InputKey(EKey::F17)  },
		{"Key F18", InputKey(EKey::F18)  },
		{"Key F19", InputKey(EKey::F19)  },
		{"Key F20", InputKey(EKey::F20)  },
		{"Key F21", InputKey(EKey::F21)  },
		{"Key F22", InputKey(EKey::F22)  },
		{"Key F23", InputKey(EKey::F23)  },
		{"Key F24", InputKey(EKey::F24)  },
		{"Key Execute", InputKey(EKey::Execute)  },
		{"Key Help", InputKey(EKey::Help)  },
		{"Key Menu", InputKey(EKey::Menu)  },
		{"Key Select", InputKey(EKey::Select)  },
		{"Key Stop", InputKey(EKey::Stop)  },
		{"Key Again", InputKey(EKey::Again)  },
		{"Key Undo", InputKey(EKey::Undo)  },
		{"Key Cut", InputKey(EKey::Cut)  },
		{"Key Copy", InputKey(EKey::Copy)  },
		{"Key Paste", InputKey(EKey::Paste)  },
		{"Key Find", InputKey(EKey::Find)  },
		{"Key Mute", InputKey(EKey::Mute)  },
		{"Key VolumeUp", InputKey(EKey::VolumeUp)  },
		{"Key VolumeDown", InputKey(EKey::VolumeDown)  },

		{"Key KP_Comma", InputKey(EKey::KP_Comma)  },
		{"Key KP_EqualsAs400", InputKey(EKey::KP_EqualsAs400)  },

		{"Key International1", InputKey(EKey::International1)  },
		{"Key International2", InputKey(EKey::International2)  },
		{"Key International3", InputKey(EKey::International3)  },
		{"Key International4", InputKey(EKey::International4)  },
		{"Key International5", InputKey(EKey::International5)  },
		{"Key International6", InputKey(EKey::International6)  },
		{"Key International7", InputKey(EKey::International7)  },
		{"Key International8", InputKey(EKey::International8)  },
		{"Key International9", InputKey(EKey::International9)  },
		{"Key Lang1", InputKey(EKey::Lang1)  },
		{"Key Lang2", InputKey(EKey::Lang2)  },
		{"Key Lang3", InputKey(EKey::Lang3)  },
		{"Key Lang4", InputKey(EKey::Lang4)  },
		{"Key Lang5", InputKey(EKey::Lang5)  },
		{"Key Lang6", InputKey(EKey::Lang6)  },
		{"Key Lang7", InputKey(EKey::Lang7)  },
		{"Key Lang8", InputKey(EKey::Lang8)  },
		{"Key Lang9", InputKey(EKey::Lang9)  },

		{"Key AltErase", InputKey(EKey::AltErase)  },
		{"Key SysReq", InputKey(EKey::SysReq)  },
		{"Key Cancel", InputKey(EKey::Cancel)  },
		{"Key Clear", InputKey(EKey::Clear)  },
		{"Key Prior", InputKey(EKey::Prior)  },
		{"Key Return2", InputKey(EKey::Return2)  },
		{"Key Seperator", InputKey(EKey::Seperator)  },
		{"Key Out", InputKey(EKey::Out)  },
		{"Key Oper", InputKey(EKey::Oper)  },
		{"Key ClearAgain", InputKey(EKey::ClearAgain)  },
		{"Key Crsel", InputKey(EKey::Crsel)  },
		{"Key Exsel", InputKey(EKey::Exsel)  },

		{"Key KP_00", InputKey(EKey::KP_00)  },
		{"Key KP_000", InputKey(EKey::KP_000)  },
		{"Key ThouseandsSeperator", InputKey(EKey::ThouseandsSeperator)  },
		{"Key DecimalSeperator", InputKey(EKey::DecimalSeperator)  },
		{"Key CurrencyUnit", InputKey(EKey::CurrencyUnit)  },
		{"Key CurrencySubUnit", InputKey(EKey::CurrencySubUnit)  },
		{"Key KP_LeftParen", InputKey(EKey::KP_LeftParen)  },
		{"Key KP_RightParen", InputKey(EKey::KP_RightParen)  },
		{"Key KP_LeftBrace", InputKey(EKey::KP_LeftBrace)  },
		{"Key KP_RightBrace", InputKey(EKey::KP_RightBrace)  },
		{"Key KP_Tab", InputKey(EKey::KP_Tab)  },
		{"Key KP_BackSpace", InputKey(EKey::KP_BackSpace)  },
		{"Key KP_A", InputKey(EKey::KP_A)  },
		{"Key KP_B", InputKey(EKey::KP_B)  },
		{"Key KP_C", InputKey(EKey::KP_C)  },
		{"Key KP_D", InputKey(EKey::KP_D)  },
		{"Key KP_E", InputKey(EKey::KP_E)  },
		{"Key KP_F", InputKey(EKey::KP_F)  },
		{"Key KP_Xor", InputKey(EKey::KP_Xor)  },
		{"Key KP_Power", InputKey(EKey::KP_Power)  },
		{"Key KP_Percent", InputKey(EKey::KP_Percent)  },
		{"Key KP_Less", InputKey(EKey::KP_Less)  },
		{"Key KP_Greater", InputKey(EKey::KP_Greater)  },
		{"Key KP_Ampersand", InputKey(EKey::KP_Ampersand)  },
		{"Key KP_DblAmpersand", InputKey(EKey::KP_DblAmpersand)  },
		{"Key KP_VerticalBar", InputKey(EKey::KP_VerticalBar)  },
		{"Key KP_DblVerticalBar", InputKey(EKey::KP_DblVerticalBar)  },
		{"Key KP_Colon", InputKey(EKey::KP_Colon)  },
		{"Key KP_Hash", InputKey(EKey::KP_Hash)  },
		{"Key KP_Space", InputKey(EKey::KP_Space)  },
		{"Key KP_At", InputKey(EKey::KP_At)  },
		{"Key KP_Exclam", InputKey(EKey::KP_Exclam)  },
		{"Key KP_MemStore", InputKey(EKey::KP_MemStore)  },
		{"Key KP_MemRecall", InputKey(EKey::KP_MemRecall)  },
		{"Key KP_MemClear", InputKey(EKey::KP_MemClear)  },
		{"Key KP_MemAdd", InputKey(EKey::KP_MemAdd)  },
		{"Key KP_MemSubtract", InputKey(EKey::KP_MemSubtract)  },
		{"Key KP_MemMultiply", InputKey(EKey::KP_MemMultiply)  },
		{"Key KP_MemDivide", InputKey(EKey::KP_MemDivide)  },
		{"Key KP_PlusMinus", InputKey(EKey::KP_PlusMinus)  },
		{"Key KP_Clear", InputKey(EKey::KP_Clear)  },
		{"Key KP_ClearEntry", InputKey(EKey::KP_ClearEntry)  },
		{"Key KP_Binary", InputKey(EKey::KP_Binary)  },
		{"Key KP_Octal", InputKey(EKey::KP_Octal)  },
		{"Key KP_Decimal", InputKey(EKey::KP_Decimal)  },
		{"Key KP_Hexadecimal", InputKey(EKey::KP_Hexadecimal)  },

		{"Key LCtrl", InputKey(EKey::LCtrl)  },
		{"Key LShift", InputKey(EKey::LShift)  },
		{"Key LAlt", InputKey(EKey::LAlt)  },
		{"Key LGui", InputKey(EKey::LGui)  },
		{"Key RCtrl", InputKey(EKey::RCtrl)  },
		{"Key RShift", InputKey(EKey::RShift)  },
		{"Key RAlt", InputKey(EKey::RAlt)  },
		{"Key RGui", InputKey(EKey::RGui)  },

		{"Key Mode", InputKey(EKey::Mode)  },

		{"Key AudioNext", InputKey(EKey::AudioNext)  },
		{"Key AudioPrev", InputKey(EKey::AudioPrev)  },
		{"Key AudioStop", InputKey(EKey::AudioStop)  },
		{"Key AudioPlay", InputKey(EKey::AudioPlay)  },
		{"Key AudioMute", InputKey(EKey::AudioMute)  },
		{"Key MediaSelect", InputKey(EKey::MediaSelect)  },
		{"Key AC_Search", InputKey(EKey::AC_Search)  },
		{"Key AC_Home", InputKey(EKey::AC_Home)  },
		{"Key AC_Back", InputKey(EKey::AC_Back)  },
		{"Key AC_Forward", InputKey(EKey::AC_Forward)  },
		{"Key AC_Stop", InputKey(EKey::AC_Stop)  },
		{"Key AC_Refresh", InputKey(EKey::AC_Refresh)  },
		{"Key AC_Bookmarks", InputKey(EKey::AC_Bookmarks)  },

		{"Key Eject", InputKey(EKey::Eject)  },
		{"Key Sleep", InputKey(EKey::Sleep)  },

		{"Key AudioRewind", InputKey(EKey::AudioRewind)  },
		{"Key AudioFastForward", InputKey(EKey::AudioFastForward)  },

		{"Mouse Invalid", InputKey(EMouse::Invalid) },
		{"Mouse Left", InputKey(EMouse::Left) },
		{"Moude Middle", InputKey(EMouse::Middle) },
		{"Mouse Right", InputKey(EMouse::Right) },
		{"Mouse X1", InputKey(EMouse::X1) },
		{"Mouse X2", InputKey(EMouse::X2) },

		{"Button Invalid", InputKey(EButton::Invalid)  },
		{"Button A", InputKey(EButton::A)  },
		{"Button B", InputKey(EButton::B)  },
		{"Button X", InputKey(EButton::X)  },
		{"Button Y", InputKey(EButton::Y)  },
		{"Button Back", InputKey(EButton::Back)  },
		{"Button Guide", InputKey(EButton::Guide)  },
		{"Button Start", InputKey(EButton::Start)  },
		{"Button LeftStick", InputKey(EButton::LeftStick)  },
		{"Button RightStick", InputKey(EButton::RightStick)  },
		{"Button LeftShoulder", InputKey(EButton::LeftShoulder)  },
		{"Button RightShoulder", InputKey(EButton::RightShoulder)  },
		{"Button DPadUp", InputKey(EButton::DPadUp)  },
		{"Button DPadDown", InputKey(EButton::DPadDown)  },
		{"Button DPadLeft", InputKey(EButton::DPadLeft)  },
		{"Button DPadRight", InputKey(EButton::DPadRight)  },
		{"Button Misc1", InputKey(EButton::Misc1)  },
		{"Button Paddle1", InputKey(EButton::Paddle1)  },
		{"Button Paddle2",  InputKey(EButton::Paddle2)  },
		{"Button Paddle3", InputKey(EButton::Paddle3)  },
		{"Button Paddle4",  InputKey(EButton::Paddle4)  },
		{"Button TouchPad", InputKey(EButton::TouchPad) }
	};
}